### PR TITLE
Add UpSetR chapter

### PR DESCRIPTION
**Pull request by PaulC91**
I _think_ I've followed the layout/formatting of the previous chapters. Let me know of any required amendments.

Cheers,
Paul

### CODE REVIEW

**Comment by hrbrmstr** [comment]
you are _almost_ done ;-)

If you could edit https://github.com/hrbrmstr/21-recipes/blob/master/index.Rmd and https://github.com/hrbrmstr/21-recipes/blob/master/00-About-the-Author.Rmd and add your name to the `author` line of the former and a short bio of yourself to the latter that'd be 👍  (need to ensure credit is given to you for this insightful addition).

**Comment by PaulC91** [comment]
Hi Bob. I'm not sure what's happened here but after editing the index.Rmd and 00-About-the-Author.Rmd as suggested, git seems to think i've modified every file in the repo! I only edited those 2 files (promise!). Maybe because I opened my rstudio project for the repo on a different computer? It seemed to immediately think all files had been modified.

Sorry about this, let me know what I need to do to fix it.

And thank you for the author credit, I feel like it's too much given my small contribution but it's greatly appreciated.

**Comment by PaulC91** [comment]
having done a bit of research it looks like it is a line ending issue having switched from windows (sorry) to mac. I'm going to try and revert the commit and sort it out. should be some good git learning experience at least!

**Comment by PaulC91** [comment]
sorted 😅 . sorry for all the spam.

Paul

**Comment by PaulC91** [comment]
Hi Bob,

Let me know if you need me to do anything more with this.

Thanks,
Paul

**Pull request merged**
